# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfrbac < Formula
  desc ""
  homepage ""
  version "0.1.11"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dev-hato/tfrbac/releases/download/v0.1.11/tfrbac_Darwin_x86_64.tar.gz"
      sha256 "cb3077393569c5a2f44532b4bb2d024e6867df98eb114ea473d102568634c007"

      def install
        bin.install "tfrbac"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dev-hato/tfrbac/releases/download/v0.1.11/tfrbac_Darwin_arm64.tar.gz"
      sha256 "547a3a01c02bd32c3f75577fcb9b4376619ee0e12db737181fb71b14152cd894"

      def install
        bin.install "tfrbac"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dev-hato/tfrbac/releases/download/v0.1.11/tfrbac_Linux_x86_64.tar.gz"
      sha256 "7d2415e8181c32d4f7863a277fd0a08464ade40feb0f9b49d777eb9cce3bf27f"

      def install
        bin.install "tfrbac"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dev-hato/tfrbac/releases/download/v0.1.11/tfrbac_Linux_arm64.tar.gz"
      sha256 "12e9ca241222107de211b2b8c1bcd36cbeaae9ff90a20b50428d1de8a4595a12"

      def install
        bin.install "tfrbac"
      end
    end
  end
end
