# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfrbac" do
  name "tfrbac"
  desc ""
  homepage ""
  version "1.0.103"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfrbac"

  on_macos do
    on_intel do
      url "https://github.com/dev-hato/tfrbac/releases/download/v#{version}/tfrbac_Darwin_x86_64.tar.gz"
      sha256 "8a2001504b322726e66a376475cae7668ea08cc645b4805c327670f5adf0867f"
    end
    on_arm do
      url "https://github.com/dev-hato/tfrbac/releases/download/v#{version}/tfrbac_Darwin_arm64.tar.gz"
      sha256 "47143ad442006dee82838a59ff8f7efabaf1508988d1d0f639ec3506b603781a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dev-hato/tfrbac/releases/download/v#{version}/tfrbac_Linux_x86_64.tar.gz"
      sha256 "b9f4e7eee1c0f0f925286ade374aa28700d6e86e25c9a56de611d684f8b7c412"
    end
    on_arm do
      url "https://github.com/dev-hato/tfrbac/releases/download/v#{version}/tfrbac_Linux_arm64.tar.gz"
      sha256 "f92235a5e3c6c1760ec20001fe9c0f2613d6c0b8cd8035d80edf06f0558b5251"
    end
  end

  # No zap stanza required
end
