# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfrbac" do
  version "1.0.177"

  on_macos do
    on_intel do
      sha256 "dd12a7df7e3a487b46928af034908d2707a7f9642d0dd93f54e33d5698690433"
      url "https://github.com/dev-hato/tfrbac/releases/download/v#{version}/tfrbac_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ea7d75fb8da9b5e6fb1f65a63235e5104f6822ce03d04d21f05b54e0cb21a713"
      url "https://github.com/dev-hato/tfrbac/releases/download/v#{version}/tfrbac_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6d7bc5b779be0c23ab7b3f5abc7af3088bc6b4c34d1a6f4134ee377d98c63c8a"
      url "https://github.com/dev-hato/tfrbac/releases/download/v#{version}/tfrbac_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bf983144cf1425811300b64daae1b4410ccb17e6bf7f98255f9514811cd4ed08"
      url "https://github.com/dev-hato/tfrbac/releases/download/v#{version}/tfrbac_Linux_arm64.tar.gz"
    end
  end

  name "tfrbac"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfrbac"

  # No zap stanza required

end
