# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfrbac" do
  name "tfrbac"
  desc ""
  homepage ""
  version "1.0.119"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfrbac"

  on_macos do
    on_intel do
      url "https://github.com/dev-hato/tfrbac/releases/download/v#{version}/tfrbac_Darwin_x86_64.tar.gz"
      sha256 "f9ee59daaaa94f1686ca6fafb1264f8aee788dda108f019c26f701785ab38bd0"
    end
    on_arm do
      url "https://github.com/dev-hato/tfrbac/releases/download/v#{version}/tfrbac_Darwin_arm64.tar.gz"
      sha256 "394427d12dfe962b411b285b069b4ecd8401629e6604c99c8eecc7164dba460d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dev-hato/tfrbac/releases/download/v#{version}/tfrbac_Linux_x86_64.tar.gz"
      sha256 "a2b958b71037acce81ece01aafbdfe2454921914ad4b97c1f5c386b5083e5065"
    end
    on_arm do
      url "https://github.com/dev-hato/tfrbac/releases/download/v#{version}/tfrbac_Linux_arm64.tar.gz"
      sha256 "44a0e8e31c9fb6c3e7739bfa077457ba67082fcbda255e43926bf15f1428f583"
    end
  end

  # No zap stanza required
end
